name: "Continuous integration"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"

    strategy:
      fail-fast: False
      matrix:
        python-version: [3.13]
        node-version: [14.x]
    
    steps:
      - name: "Clone Repository"
        uses: actions/checkout@v4
      
      - name: "Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: "Install node.js dependencies"
        run: npm install
        working-directory: ./src

      - name: "Build React app"
        run: npm run build
        working-directory: ./src
      
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      
      - name: "Create Virtual environment"
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: "Install dependencies"
        run: |
          pip install -r backend/requirements.txt
        
      - name: "Run Api_Testing"
        run: python backend/api_testing.py

        
  

