name: "Python Continuous integration"

on:
  push:
    branches:
      - main
  pull_request:  
  workflow_dispatch:

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"

    strategy:
      fail-fast: False
      matrix:
        python-version: [3.13]
    
    steps:
      - name: "Clone Repository"
        uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      
      - name: "Create Virtual environment"
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: "Install dependencies"
        run: |
          pip install -r backend/requirements.txt
        
      - name: "Run Api_Testing"
        run: python backend/api_testing.py

        
  

