name: "React"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"

    strategy:
      fail-fast: False
      matrix:
        node-version: [14.x]
    
    steps:
      - name: "Clone Repository"
        uses: actions/checkout@v4
      
      - name: "Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: "Install node.js dependencies"
        run: npm install
        working-directory: ./src

      - name: "Build React app"
        run: npm run build
        working-directory: ./src

        
  

